// Dave Johnson
// 09/19/12
// Visual Frameworks 1209
// Assignment 4

var json = {
    "Order1": {
        "firstname": ["First Name:", "Joe"],
        "lastname": ["Last Name:", "Soreaka"],
        "address": ["Address:", "353 Nomei St."],
        "city": ["City:", "Arcadia"],
        "select": ["State:", "FL"],
        "phnumber": ["Phone Number:", "(184)943-3983"],
        "crust": ["Crust:", "No Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "No"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "19"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-30"],
        "instruct": ["Special Instructions:", "ASAP"]
    },
    "Order2": {
        "firstname": ["First Name:", "Tammy"],
        "lastname": ["Last Name:", "Jeafilo"],
        "address": ["Address:", "94 Rocky Road Ave."],
        "city": ["City:", "Denver"],
        "select": ["State:", "CO"],
        "phnumber": ["Phone Number:", "(974)389-1937"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "None"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "No"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "7"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Tomorrow is fine."]
    },
    "Order3": {
        "firstname": ["First Name:", "Jeanette"],
        "lastname": ["Last Name:", "Cerodas"],
        "address": ["Address:", "94814 Savvy Port Dr."],
        "city": ["City:", "Rangeport"],
        "select": ["State:", "IA"],
        "phnumber": ["Phone Number:", "(892)310-9037"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "Yes"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "3"],
        "method": ["Method:", "Deliver"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Whenever."]
    },
    "Order4": {
        "firstname": ["First Name:", "Rick"],
        "lastname": ["Last Name:", "Ottomen"],
        "address": ["Address:", "1234 Wild Road Dr."],
        "city": ["City:", "Novi"],
        "select": ["State:", "MI"],
        "phnumber": ["Phone Number:", "(345)234-3596"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "16"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "I want it now!"]
    }
}